version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://agnanimayur:0YfnfbZWmMQfC6Vc@cluster0.d7w8l8l.mongodb.net/user_db"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  mongo-data:
